import type { CatalogProblem, Difficulty } from '../types';
import { uid } from './id';

// NeetCode 150 practice checklist (https://neetcode.io/practice) — editable in
// the DSA section. Problems auto-check when you log a matching daily solve.
const LIST: Array<[string, string, Difficulty]> = [
  // Arrays & Hashing
  ['Arrays & Hashing', 'Contains Duplicate', 'Easy'],
  ['Arrays & Hashing', 'Valid Anagram', 'Easy'],
  ['Arrays & Hashing', 'Two Sum', 'Easy'],
  ['Arrays & Hashing', 'Group Anagrams', 'Medium'],
  ['Arrays & Hashing', 'Top K Frequent Elements', 'Medium'],
  ['Arrays & Hashing', 'Product of Array Except Self', 'Medium'],
  ['Arrays & Hashing', 'Encode and Decode Strings', 'Medium'],
  ['Arrays & Hashing', 'Valid Sudoku', 'Medium'],
  ['Arrays & Hashing', 'Longest Consecutive Sequence', 'Medium'],
  // Two Pointers
  ['Two Pointers', 'Valid Palindrome', 'Easy'],
  ['Two Pointers', 'Two Sum II - Input Array Is Sorted', 'Medium'],
  ['Two Pointers', '3Sum', 'Medium'],
  ['Two Pointers', 'Container With Most Water', 'Medium'],
  ['Two Pointers', 'Trapping Rain Water', 'Hard'],
  // Sliding Window
  ['Sliding Window', 'Best Time to Buy and Sell Stock', 'Easy'],
  ['Sliding Window', 'Longest Substring Without Repeating Characters', 'Medium'],
  ['Sliding Window', 'Longest Repeating Character Replacement', 'Medium'],
  ['Sliding Window', 'Permutation in String', 'Medium'],
  ['Sliding Window', 'Minimum Window Substring', 'Hard'],
  ['Sliding Window', 'Sliding Window Maximum', 'Hard'],
  // Stack
  ['Stack', 'Valid Parentheses', 'Easy'],
  ['Stack', 'Min Stack', 'Medium'],
  ['Stack', 'Evaluate Reverse Polish Notation', 'Medium'],
  ['Stack', 'Generate Parentheses', 'Medium'],
  ['Stack', 'Daily Temperatures', 'Medium'],
  ['Stack', 'Car Fleet', 'Medium'],
  ['Stack', 'Largest Rectangle in Histogram', 'Hard'],
  // Binary Search
  ['Binary Search', 'Binary Search', 'Easy'],
  ['Binary Search', 'Search a 2D Matrix', 'Medium'],
  ['Binary Search', 'Koko Eating Bananas', 'Medium'],
  ['Binary Search', 'Find Minimum in Rotated Sorted Array', 'Medium'],
  ['Binary Search', 'Search in Rotated Sorted Array', 'Medium'],
  ['Binary Search', 'Time Based Key-Value Store', 'Medium'],
  ['Binary Search', 'Median of Two Sorted Arrays', 'Hard'],
  // Linked List
  ['Linked List', 'Reverse Linked List', 'Easy'],
  ['Linked List', 'Merge Two Sorted Lists', 'Easy'],
  ['Linked List', 'Reorder List', 'Medium'],
  ['Linked List', 'Remove Nth Node From End of List', 'Medium'],
  ['Linked List', 'Copy List with Random Pointer', 'Medium'],
  ['Linked List', 'Add Two Numbers', 'Medium'],
  ['Linked List', 'Find the Duplicate Number', 'Medium'],
  ['Linked List', 'LRU Cache', 'Medium'],
  ['Linked List', 'Merge K Sorted Lists', 'Hard'],
  ['Linked List', 'Reverse Nodes in K-Group', 'Hard'],
  // Trees
  ['Trees', 'Invert Binary Tree', 'Easy'],
  ['Trees', 'Maximum Depth of Binary Tree', 'Easy'],
  ['Trees', 'Diameter of Binary Tree', 'Easy'],
  ['Trees', 'Balanced Binary Tree', 'Easy'],
  ['Trees', 'Same Tree', 'Easy'],
  ['Trees', 'Subtree of Another Tree', 'Easy'],
  ['Trees', 'Lowest Common Ancestor of a BST', 'Medium'],
  ['Trees', 'Binary Tree Level Order Traversal', 'Medium'],
  ['Trees', 'Validate Binary Search Tree', 'Medium'],
  ['Trees', 'Kth Smallest Element in a BST', 'Medium'],
  ['Trees', 'Construct Tree from Preorder and Inorder', 'Medium'],
  ['Trees', 'Binary Tree Maximum Path Sum', 'Hard'],
  ['Trees', 'Serialize and Deserialize Binary Tree', 'Hard'],
  // Tries
  ['Tries', 'Implement Trie (Prefix Tree)', 'Medium'],
  ['Tries', 'Design Add and Search Words Data Structure', 'Medium'],
  ['Tries', 'Word Search II', 'Hard'],
  // Heap / Priority Queue
  ['Heap / Priority Queue', 'Kth Largest Element in a Stream', 'Easy'],
  ['Heap / Priority Queue', 'Last Stone Weight', 'Easy'],
  ['Heap / Priority Queue', 'K Closest Points to Origin', 'Medium'],
  ['Heap / Priority Queue', 'Kth Largest Element in an Array', 'Medium'],
  ['Heap / Priority Queue', 'Task Scheduler', 'Medium'],
  ['Heap / Priority Queue', 'Find Median from Data Stream', 'Hard'],
  // Backtracking
  ['Backtracking', 'Subsets', 'Medium'],
  ['Backtracking', 'Combination Sum', 'Medium'],
  ['Backtracking', 'Permutations', 'Medium'],
  ['Backtracking', 'Subsets II', 'Medium'],
  ['Backtracking', 'Combination Sum II', 'Medium'],
  ['Backtracking', 'Word Search', 'Medium'],
  ['Backtracking', 'Palindrome Partitioning', 'Medium'],
  ['Backtracking', 'Letter Combinations of a Phone Number', 'Medium'],
  ['Backtracking', 'N-Queens', 'Hard'],
  // Graphs
  ['Graphs', 'Number of Islands', 'Medium'],
  ['Graphs', 'Max Area of Island', 'Medium'],
  ['Graphs', 'Clone Graph', 'Medium'],
  ['Graphs', 'Walls and Gates', 'Medium'],
  ['Graphs', 'Rotting Oranges', 'Medium'],
  ['Graphs', 'Pacific Atlantic Water Flow', 'Medium'],
  ['Graphs', 'Surrounded Regions', 'Medium'],
  ['Graphs', 'Course Schedule', 'Medium'],
  ['Graphs', 'Course Schedule II', 'Medium'],
  ['Graphs', 'Redundant Connection', 'Medium'],
  ['Graphs', 'Number of Connected Components', 'Medium'],
  ['Graphs', 'Graph Valid Tree', 'Medium'],
  ['Graphs', 'Word Ladder', 'Hard'],
  // Advanced Graphs
  ['Advanced Graphs', 'Alien Dictionary', 'Hard'],
  ['Advanced Graphs', 'Network Delay Time', 'Medium'],
  ['Advanced Graphs', 'Cheapest Flights Within K Stops', 'Medium'],
  ['Advanced Graphs', 'Swim in Rising Water', 'Hard'],
  ['Advanced Graphs', 'Min Cost to Connect All Points', 'Medium'],
  ['Advanced Graphs', 'Reconstruct Itinerary', 'Hard'],
  // 1-D DP
  ['1-D Dynamic Programming', 'Climbing Stairs', 'Easy'],
  ['1-D Dynamic Programming', 'Min Cost Climbing Stairs', 'Easy'],
  ['1-D Dynamic Programming', 'House Robber', 'Medium'],
  ['1-D Dynamic Programming', 'House Robber II', 'Medium'],
  ['1-D Dynamic Programming', 'Longest Palindromic Substring', 'Medium'],
  ['1-D Dynamic Programming', 'Palindromic Substrings', 'Medium'],
  ['1-D Dynamic Programming', 'Decode Ways', 'Medium'],
  ['1-D Dynamic Programming', 'Coin Change', 'Medium'],
  ['1-D Dynamic Programming', 'Maximum Product Subarray', 'Medium'],
  ['1-D Dynamic Programming', 'Word Break', 'Medium'],
  ['1-D Dynamic Programming', 'Longest Increasing Subsequence', 'Medium'],
  ['1-D Dynamic Programming', 'Partition Equal Subset Sum', 'Medium'],
  // 2-D DP
  ['2-D Dynamic Programming', 'Unique Paths', 'Medium'],
  ['2-D Dynamic Programming', 'Longest Common Subsequence', 'Medium'],
  ['2-D Dynamic Programming', 'Best Time to Buy and Sell Stock with Cooldown', 'Medium'],
  ['2-D Dynamic Programming', 'Coin Change II', 'Medium'],
  ['2-D Dynamic Programming', 'Target Sum', 'Medium'],
  ['2-D Dynamic Programming', 'Interleaving String', 'Medium'],
  ['2-D Dynamic Programming', 'Longest Increasing Path in a Matrix', 'Hard'],
  ['2-D Dynamic Programming', 'Distinct Subsequences', 'Hard'],
  ['2-D Dynamic Programming', 'Edit Distance', 'Medium'],
  ['2-D Dynamic Programming', 'Burst Balloons', 'Hard'],
  ['2-D Dynamic Programming', 'Regular Expression Matching', 'Hard'],
  // Greedy
  ['Greedy', 'Maximum Subarray', 'Medium'],
  ['Greedy', 'Jump Game', 'Medium'],
  ['Greedy', 'Jump Game II', 'Medium'],
  ['Greedy', 'Gas Station', 'Medium'],
  ['Greedy', 'Hand of Straights', 'Medium'],
  ['Greedy', 'Merge Triplets to Form Target', 'Medium'],
  ['Greedy', 'Partition Labels', 'Medium'],
  ['Greedy', 'Valid Parenthesis String', 'Medium'],
  // Intervals
  ['Intervals', 'Insert Interval', 'Medium'],
  ['Intervals', 'Merge Intervals', 'Medium'],
  ['Intervals', 'Non-overlapping Intervals', 'Medium'],
  ['Intervals', 'Meeting Rooms', 'Easy'],
  ['Intervals', 'Meeting Rooms II', 'Medium'],
  ['Intervals', 'Minimum Interval to Include Each Query', 'Hard'],
  // Math & Geometry
  ['Math & Geometry', 'Rotate Image', 'Medium'],
  ['Math & Geometry', 'Spiral Matrix', 'Medium'],
  ['Math & Geometry', 'Set Matrix Zeroes', 'Medium'],
  ['Math & Geometry', 'Happy Number', 'Easy'],
  ['Math & Geometry', 'Plus One', 'Easy'],
  ['Math & Geometry', 'Pow(x, n)', 'Medium'],
  ['Math & Geometry', 'Multiply Strings', 'Medium'],
  ['Math & Geometry', 'Detect Squares', 'Medium'],
  // Bit Manipulation
  ['Bit Manipulation', 'Single Number', 'Easy'],
  ['Bit Manipulation', 'Number of 1 Bits', 'Easy'],
  ['Bit Manipulation', 'Counting Bits', 'Easy'],
  ['Bit Manipulation', 'Reverse Bits', 'Easy'],
  ['Bit Manipulation', 'Missing Number', 'Easy'],
  ['Bit Manipulation', 'Sum of Two Integers', 'Medium'],
  ['Bit Manipulation', 'Reverse Integer', 'Medium'],
];

export function seedCatalog(): CatalogProblem[] {
  return LIST.map(([topic, name, difficulty]) => ({
    id: uid('p'),
    name,
    difficulty,
    topic,
    solved: false,
  }));
}

export function normalizeName(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, '');
}
